version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: esbuild
    versions:
    - 0.11.0
    - 0.11.12
    - 0.11.2
    - 0.11.5
    - 0.11.9
    - 0.8.54
    - 0.8.57
    - 0.9.2
    - 0.9.6
  - dependency-name: vite-plugin-windicss
    versions:
    - 0.11.1
    - 0.11.3
    - 0.12.5
    - 0.14.0
    - 0.14.6
    - 0.6.2
    - 0.7.1
    - 0.8.3
    - 0.9.6
  - dependency-name: rollup-plugin-esbuild
    versions:
    - 2.2.0
    - 4.0.1
  - dependency-name: "@types/marked"
    versions:
    - 1.2.1
    - 1.2.2
    - 2.0.0
    - 2.0.1
  - dependency-name: type-fest
    versions:
    - 0.20.2
    - 0.21.1
    - 0.21.2
    - 0.21.3
    - 1.0.0
    - 1.0.1
  - dependency-name: rollup-plugin-dts
    versions:
    - 3.0.1
  - dependency-name: rollup-plugin-postcss
    versions:
    - 4.0.0
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.2.0
  - dependency-name: marked
    versions:
    - 2.0.0
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 17.0.0
    - 17.1.0
  - dependency-name: tailwindcss
    versions:
    - 1.9.6
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
